language: python

python:
- "3.3"
- "3.4"
- "3.5"
- "3.6"

sudo: required

env:
- ABYSMAL_STRICT=1
- ABYSMAL_COVER=1 ABYSMAL_DEBUG=1

before_install: travis/before_install.sh
install: travis/install.sh
script: travis/script.sh
after_success: travis/after_success.sh