language: python

python:
- "3.5"
- "3.6"

addons:
  apt:
    source:
    - python3-dev
    - libmpdec-dev

before_install: travis/before_install.sh
install: travis/install.sh
script: travis/script.sh
after_success: travis/after_success.sh